name = "ticketing-docs"
compatibility_date = "2026-02-09"

[assets]
directory = "./_site"
# binding = "ASSETS"  <-- The offending line is gone.

[[routes]]
pattern = "docs.ktckts.com"
custom_domain = true