using System.Net.Http;
using System.Text;
using Ticketing.Integrations.AsynchronousIntegrations.Crm.Mailchimp.Api.Models;

namespace Ticketing.Integrations.AsynchronousIntegrations.Crm.Mailchimp.Api;

/// <summary>
/// The exception that comes back from Mail Chimp when an invalid operation has occurred.
/// </summary>
public class MailChimpException : Exception
{
	public MailChimpException(
		string? prefix,
		MailChimpApiError apiError,
		HttpResponseMessage? rawHttpResponseMessage = null) : base((prefix != null ? $"{prefix} " : "") + FormatMessage(apiError, rawHttpResponseMessage))
	{
		Detail = apiError.Detail;
		Title = apiError.Title;
		Type = apiError.Type;
		Status = apiError.Status;
		Instance = apiError.Instance;
		Errors = apiError.Errors;

		RawHttpResponseMessage = rawHttpResponseMessage;
	}
	public MailChimpException(
		MailChimpApiError apiError,
		HttpResponseMessage? rawHttpResponseMessage = null) : this(prefix: null, apiError, rawHttpResponseMessage)
	{
	}

	private static string FormatMessage(
		MailChimpApiError apiError,
		HttpResponseMessage? rawHttpResponseMessage)
	{
		StringBuilder builder = new();
		builder.AppendLine($"Title: {apiError.Title}");
		builder.AppendLine($"Type: {apiError.Type}");
		builder.AppendLine($"Status: {apiError.Status}");
		builder.AppendLine($"Instance: {apiError.Instance}");
		builder.AppendLine($"Detail: {apiError.Detail}");
		builder.AppendLine("Errors: " + string.Join(" : ", apiError.Errors.Select(x => x.Field + " " + x.Message)));

		if (rawHttpResponseMessage != null)
			builder.AppendLine("Request URI:" + rawHttpResponseMessage.RequestMessage?.RequestUri);

		return builder.ToString();
	}

	private IDictionary? data;

	public List<MailChimpError> Errors { get; set; }

	/// <summary>
	/// Gets or Sets a human-readable explanation specific to this occurrence of the problem. Learn more about errors.
	/// </summary>
	public string Detail { get; set; }

	/// <summary>
	/// Gets or sets a string that identifies this specific occurrence of the problem. Please provide this ID when contacting support.
	/// </summary>
	public string Instance { get; set; }

	/// <summary>
	/// Gets or sets the HTTP status code (RFC2616, Section 6) generated by the origin server for this occurrence of the problem.
	/// </summary>
	public int Status { get; set; }

	/// <summary>
	/// Gets or sets a short, human-readable summary of the problem type. It shouldn't change based on the occurrence of the problem, except for purposes of localization.
	/// </summary>
	public string Title { get; set; }

	/// <summary>
	/// Gets or sets an absolute URI that identifies the problem type. When dereferenced, it should provide human-readable documentation for the problem type.
	/// </summary>
	public string Type { get; set; }

	/// <summary>
	/// Gets or Sets the raw http response message.
	/// </summary>
	public HttpResponseMessage? RawHttpResponseMessage { get; set; }

	public override IDictionary Data
	{
		get
		{
			if (this.data != null)
				return this.data;

			var data = base.Data;
			data.Add("detail", Detail);
			data.Add("title", Title);
			data.Add("type", Type);
			data.Add("status", Status);
			data.Add("instance", Instance);
			data.Add("errors", Errors);
			data.Add("rawhttpresponsemessage", RawHttpResponseMessage);

			this.data = data;
			return this.data;
		}
	}
}